{
    "name": "Master Data Inkindo",
    "version": "1.01",
    "author": "Fits! Team - by PT. Fujicon Priangan Perdana",
    "license": "",
    "category": "Data",
    "website": "http://fujicon-japan.com",
    "depends": ['membership'],
    "data": [
             'security/ir.model.access.csv',
             'views/dipa3.xml',
             'views/edu.xml',
             'views/dipa4.xml',
             'views/dipa5_6.xml',
             'views/dipa7_7a.xml',
             'views/dipa8a_8b.xml',
             'views/dipa99a_1010a.xml',
             'views/dipa11_12_13.xml',
             'views/dipa14_15_16_17.xml',
             'views/dok_perusahaan.xml',
             'views/member_view.xml',
             ],
    'installable': True,
    'auto_install': False,
}